### ISSUE TITLE
Readme com install guide?

### ISSUE THREAD

**Issue by viniciusgati** [danielflira/language-advpl#1]
Seria ótimo poder usar, mas não se sabe como instalar e também não está no repositório oficial, pretende colocar?

**Comment by danielflira** [comment]
Para instalar apenas ir no atom nas preferencia (settings) <ctrl+,> no menu lateral clicar em instalar (install), na caixa de texto apenas colar o link do repositorio (https://github.com/danielflira/language-advpl) e selecionar a opção instalar.

Adicionada informação no readme
